import { ConnectButton } from '@rainbow-me/rainbowkit';
import Head from 'next/head';

const Home = () => {
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <ConnectButton />
    </div>
  );
};

export default Home;
